steps:
  # Build new Docker image
  - id: "build"
    name: 'gcr.io/cloud-builders/docker'
    env:
      - 'DOCKER_BUILDKIT=1'
      - 'OSDK_GENERATE_TOKEN=$_OSDK_GENERATE_TOKEN'
      - 'OSDK_INDEX_URL=$_OSDK_INDEX_URL'
      - 'OSDK_EXTRA_INDEX_URL=$_OSDK_EXTRA_INDEX_URL'
    args:
      - 'build'
      - '--secret'
      - 'id=osdk_generate_token,env=OSDK_GENERATE_TOKEN'
      - '--secret'
      - 'id=osdk_index_url,env=OSDK_INDEX_URL'
      - '--secret'
      - 'id=osdk_extra_index_url,env=OSDK_EXTRA_INDEX_URL'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/general-walarus-registry/general-walarus:latest'
      - '.'
  # Push new Docker image to registry
  - id: "push"
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/general-walarus-registry/general-walarus:latest'
  # Kickoff deploy trigger
  - id: "trigger-deploy"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: bash
    args:
      - -c
      - |
        gcloud builds submit \
        --config ci/deploy.yaml \
        --no-source \
        --substitutions='_BW_API_URL=$_BW_API_URL,_BW_ID_URL=$_BW_ID_URL,_BW_ACCESS_TOKEN=$_BW_ACCESS_TOKEN,_ENVIRONMENT=$_ENVIRONMENT'

options:
  logging: CLOUD_LOGGING_ONLY
