steps:
  # Build new Docker image
  - id: "build"
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/general-walarus-registry/general-walarus:latest'
      - '.'
  # Push new Docker image to registry
  - id: "push"
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/general-walarus-registry/general-walarus:latest'
  # Kickoff deploy trigger
  - id: "trigger-deploy"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: bash
    args:
      - -c
      - |
        gcloud builds submit \
        --config ci/deploy.yaml \
        --substitutions=_BOT_TOKEN=$_BOT_TOKEN,_DB_CONN_STRING=$_DB_CONN_STRING,_ARCHIVE_DATE_ID=$_ARCHIVE_DATE_ID,_OPENAI_API_KEY=$_OPENAI_API_KEY,_OPENAI_ASST_ID=$_OPENAI_ASST_ID,_OPENAI_MODEL=$_OPENAI_MODEL
        .

options:
  logging: CLOUD_LOGGING_ONLY
